### PR TITLE
2016-05-25a

### PR DESCRIPTION
**Pull request by tkelman**
Brought to you by https://github.com/JuliaCI/PackageEvaluator.jl/blob/master/scripts/cronjob.jl - slightly modified to push to a branch while I'm still testing it out. Should have it running as a cron job once I move things over to nanosoldier1.

### CODE REVIEW

**Comment by tkelman** [comment]
running more often, already useful in identifying which packages were using `showcompact_lim`

**Comment by IainNZ** [comment]
What happens in the event of a "freeze"? Will that cron job deal with it?

**Comment by IainNZ** [comment]
Oh and did a solution to the "twice a day making a mess of history" thing ever get resolved?

**Comment by tkelman** [comment]
Dunno yet. Will keep an eye on it, let's find out. I actually ran this with the runvagrant part commented out for this test. I'm running again including the runvagrant part, in a way that will commit to a branch, to see what happens if we have multiple runs per day.

**Pull request merged**
