### PR TITLE
Include inpage links.

### PR DESCRIPTION
**Pull request by ivarne**
Not sure if this works. (have not found out how to test it) The marker character should probably be colored in background color when the mouse is not hovering the link.

### CODE REVIEW

**Comment by IainNZ** [comment]
Is this so someone could provide a link to a specific package?

**Comment by ivarne** [comment]
Yes, like the part after the `#` in http://docs.julialang.org/en/latest/manual/functions/#operators-with-special-names.

**Comment by IainNZ** [comment]
I think if we had that then it'd need to include which version of Julia its for too, and that if you load the page then it ensures that package is visible - otherwise you could follow the link and see nothing

**Comment by ivarne** [comment]
That sounds reasonable.

**Comment by ivarne** [comment]
Now I have something that seems to be partially correct, but it does not work on new pageloads

**Comment by IainNZ** [comment]
Not applicable anymore

**Pull request closed without merging**
